#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config bottom_padding 10
bspc config top_padding 10
bspc config left_padding 10
bspc config right_padding 10

picom --experimental-backend &
# picom &
# $HOME/.config/polybar/launch.sh --forest
# polybar --config=$HOME/.config/polybar/config bar
tint2 &
feh --bg-scale Downloads/Wallpapers/anime_girl.jpg

amixer set Capture 27%
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Code desktop='^2'
